#!/bin/sh

RUBY_VERSION="2.7.0"
NODEJS_VERSION="12.16.1"
PYTHON_VERSION="3.8.1"
PYTHON2_VERSION="2.7.17"

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
  # Install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi
fi

# Update yadm origin URL
yadm remote set-url origin "git@github.com:TiuTalk/.dotfiles.git"

# Install Ruby
if ! (asdf plugin list | grep ruby) >/dev/null 2>&1; then
  echo "Installing Ruby $RUBY_VERSION through asdf"
  asdf plugin-add ruby
  asdf install ruby $RUBY_VERSION
  asdf global ruby $RUBY_VERSION
fi

# Install NodeJS
if ! (asdf plugin list | grep nodejs) >/dev/null 2>&1; then
  echo "Installing NodeJS $NODEJS_VERSION through asdf"
  asdf plugin-add nodejs
  bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
  asdf install nodejs $NODEJS_VERSION
  asdf global nodejs $NODEJS_VERSION
fi

# Install Python
if ! (asdf plugin list | grep python) >/dev/null 2>&1; then
  echo "Installing Python $PYTHON_VERSION through asdf"
  asdf plugin-add python
  asdf install python $PYTHON_VERSION
  asdf install python $PYTHON2_VERSION
  asdf global python $PYTHON_VERSION $PYTHON2_VERSION
fi
